x-common-variables: &common-variables
  PROFILE_SERVICE_URI: http://profile-service:8080
  AUTH_SERVICE_URI: http://auth-service:3000

services:
  mongodb-service:
    image: mongo:latest
    container_name: mongodb-service
    hostname: mongodb-service
    restart: always
    networks:
      services-network:
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  session-service:
    image: ghcr.io/letsstreamit/session-service:main
    container_name: session-service
    hostname: session-service
    restart: always
    networks:
      services-network:
    environment:
      PORT: 4000
      <<: *common-variables

  frontend-service:
    image: ghcr.io/letsstreamit/frontend-service:main
    # build:
    #   context: frontend-service
    #   dockerfile: Dockerfile
    container_name: frontend-service
    hostname: frontend-service
    restart: always
    networks:
      services-network:
    ports:
      - "80:80"
    environment:
      PORT: 80
      VITE_PROFILE_SERVICE_HOSTNAME: profile-service
      VITE_PROFILE_SERVICE_PORT: 8080
      VITE_AUTH_SERVICE_HOSTNAME: auth-service
      VITE_AUTH_SERVICE_PORT: 3000
      VITE_SESSION_SERVICE_HOSTNAME: session-service
      VITE_SESSION_SERVICE_PORT: 4000
      VITE_YOUTUBE_API_KEY: ${YOUTUBE_API_KEY} # Set this in your .env file

  auth-service:
    image: ghcr.io/letsstreamit/auth-service:main
    depends_on:
      mongodb-service:
        condition: service_healthy
    # build:
    #   context: auth-service
    #   dockerfile: Dockerfile
    container_name: auth-service
    hostname: auth-service
    restart: always
    ports:
      - "3000:3000"
    networks:
      services-network:
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET} # Set this in your .env file
      MONGO_URI: mongodb://mongodb-service:27017/auth-db
      <<: *common-variables

  profile-service:
    image: ghcr.io/letsstreamit/profile-service:latest
    # build:
    #   context: profile-service
    #   dockerfile: target/docker/stage/Dockerfile
    depends_on:
      mongodb-service:
        condition: service_healthy
    container_name: profile-service
    hostname: profile-service
    restart: always
    ports:
      - "8081:8080"
    networks:
      services-network:
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb-service:27017/profile-db
      AKKA_LICENSE_KEY: ${AKKA_LICENSE_KEY} # Set this in your .env file
      <<: *common-variables
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]

networks:
  services-network:
    driver: bridge
