x-common-variables: &common-variables
    MONGO_URI: mongodb://localhost:27017/
    JWT_SECRET: supersecret
    PROFILE_SERVICE_URI: http://profile-service:8080
    AUTH_SERVICE_URI: http://profile-service:3000

services:
  mongodb-service:
    hostname: mongodb-service
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  
  session-service:
    hostname: session-service
    image: ghcr.io/letsstreamit/session-service:main
    container_name: session-service
    restart: always
    environment:
      PORT: 4000
      <<: *common-variables
 
  frontend-service:
    hostname: frontend-service
    image: ghcr.io/letsstreamit/frontend-service:main
    container_name: frontend-service
    restart: always
    environment:
      PORT: 5173
      <<: *common-variables

  auth-service:
    hostname: auth-service
    image: ghcr.io/letsstreamit/profile-service:main
    container_name: auth-service
    restart: always
    environment:
      PORT: 3000
      <<: *common-variables


  profile-service:
    hostname: profile-service
    image: ghcr.io/letsstreamit/profile-service:main
    container_name: profile-service
    restart: always
    environment:
      PORT: 8080
      AKKA_LICENSE_KEY: ${AKKA_LICENSE_KEY} # Set this in your .env file
      <<: *common-variables
